
/* Automatically generated struct definitions for the Data API.
   Do not edit manually, changes will be overwritten.           */

package blender.makesrna.srna;

import blender.makesdna.sdna.*;

import static blender.makesrna.RnaRna.*;
import static blender.makesrna.RnaAccess.*;
import static blender.makesrna.RnaDefine.*;
import static blender.makesrna.RNATypes.*;
import blender.makesrna.RNATypes.PointerRNA;
import blender.makesrna.rna_internal_types.*;
import blender.blenlib.*;
import blender.blenkernel.*;

import static blender.makesrna.RnaObjectUtil.*;
import static blender.makesrna.RnaObjectApi.*;

public class RnaObject extends RnaStruct {
	
public RnaObject getParent() {
//	if (ptr.data != null)
		return new RnaObject(new PointerRNA(RNA_Object, ((bObject)ptr.data).parent));
//	else return null;
}

public String getParent_type() {
//	if (ptr.data != null)
		return EnumPropertyItem.name(rna_Object_parent_type_items, ((bObject)ptr.data).partype);
//	else return null;
}

public String getRotation_mode() {
//	if (ptr.data != null)
		return EnumPropertyItem.name(rna_Object_rotation_mode_items, ((bObject)ptr.data).rotmode);
//	else return null;
}

public String getDupli_type() {
//	if (ptr.data != null)
		return EnumPropertyItem.name(rna_Object_dupli_type_items, ((bObject)ptr.data).transflag);
//	else return null;
}

public String getType() {
	if ((bObject)ptr.data != null)
		return EnumPropertyItem.name(rna_Object_type_items, ((bObject)ptr.data).type);
	else
		return EnumPropertyItem.name(rna_Object_type_items, 0);
}

public String getName() {
	return StringUtil.toJString(((bObject)ptr.data).name,0);
}

public boolean getShow_bounds() {
	return ((bObject)ptr.data).dtx!=0;
}

/* Autogenerated Functions */

public RnaObject(PointerRNA ptr) {
	super(ptr);
//	if (ptr.data == null)
//		Thread.dumpStack();
}

private static PropCollectionGetFunc Object_rna_properties_get = new PropCollectionGetFunc() {
public PointerRNA get(CollectionPropertyIterator iter)
{
	return rna_builtin_properties_get.get(iter);
}};

private static PropCollectionBeginFunc Object_rna_properties_begin = new PropCollectionBeginFunc() {
public void begin(CollectionPropertyIterator iter, PointerRNA ptr)
{

	iter.clear();
	iter.parent= ptr;
	iter.prop= (PropertyRNA)rna_Object_rna_properties;

	rna_builtin_properties_begin.begin(iter, ptr);

	if(iter.valid)
		iter.ptr= Object_rna_properties_get.get(iter);
}};

private static PropCollectionNextFunc Object_rna_properties_next = new PropCollectionNextFunc() {
public void next(CollectionPropertyIterator iter)
{
	rna_builtin_properties_next.next(iter);

	if(iter.valid)
		iter.ptr= Object_rna_properties_get.get(iter);
}};

private static PropCollectionEndFunc Object_rna_properties_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
	rna_iterator_listbase_end.end(iter);
}};

private static PropPointerGetFunc Object_rna_type_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_builtin_type_get.getPtr(ptr);
}};

private static PropPointerSetFunc Object_data_set = new PropPointerSetFunc() {
public void setPtr(PointerRNA ptr, PointerRNA value)
{
	rna_Object_data_set.setPtr(ptr, value);
}};

public static PropFloatArrayGetFunc Object_bound_box_get = new PropFloatArrayGetFunc() {
public void getFloatArray(PointerRNA ptr, float[] values)
{
	rna_Object_boundbox_get.getFloatArray(ptr, values);
}};

private static PropPointerSetFunc Object_parent_set = new PropPointerSetFunc() {
public void setPtr(PointerRNA ptr, PointerRNA value)
{
	rna_Object_parent_set.setPtr(ptr, value);
}};

public void setParent_type(int value) { Object_parent_type_set.setEnum(ptr, value); }
private static PropEnumSetFunc Object_parent_type_set = new PropEnumSetFunc() {
public void setEnum(PointerRNA ptr, int value)
{
	rna_Object_parent_type_set.setEnum(ptr, value);
}};

public void setParent_bone(String value) { Object_parent_bone_set.setStr(ptr, StringUtil.toCString(value),0); }
private static PropStringSetFunc Object_parent_bone_set = new PropStringSetFunc() {
public void setStr(PointerRNA ptr, byte[] value, int offset)
{
	rna_Object_parent_bone_set.setStr(ptr, value, offset);
}};

private static PropCollectionGetFunc Object_material_slots_get = new PropCollectionGetFunc() {
public PointerRNA get(CollectionPropertyIterator iter)
{
//	return rna_pointer_inherit_refine(iter.parent, RNA_MaterialSlot, rna_iterator_array_get.get(iter));
	return null;
}};

private static PropCollectionEndFunc Object_material_slots_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
}};

private static PropPointerGetFunc Object_active_material_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_Object_active_material_get.getPtr(ptr);
}};

private static PropPointerSetFunc Object_active_material_set = new PropPointerSetFunc() {
public void setPtr(PointerRNA ptr, PointerRNA value)
{
	rna_Object_active_material_set.setPtr(ptr, value);
}};

public int getActive_material_index() { return Object_active_material_index_get.getInt(ptr); }
private static PropIntGetFunc Object_active_material_index_get = new PropIntGetFunc() {
public int getInt(PointerRNA ptr)
{
	return rna_Object_active_material_index_get.getInt(ptr);
}};

public void setActive_material_index(int value) { Object_active_material_index_set.setInt(ptr, value); }
private static PropIntSetFunc Object_active_material_index_set = new PropIntSetFunc() {
public void setInt(PointerRNA ptr, int value)
{
	rna_Object_active_material_index_set.setInt(ptr, value);
}};

public void setRotation_mode(int value) { Object_rotation_mode_set.setEnum(ptr, value); }
private static PropEnumSetFunc Object_rotation_mode_set = new PropEnumSetFunc() {
public void setEnum(PointerRNA ptr, int value)
{
	rna_Object_rotation_mode_set.setEnum(ptr, value);
}};

public static PropFloatArrayGetFunc Object_matrix_local_get = new PropFloatArrayGetFunc() {
public void getFloatArray(PointerRNA ptr, float[] values)
{
	rna_Object_matrix_local_get.getFloatArray(ptr, values);
}};

public static PropFloatArraySetFunc Object_matrix_local_set = new PropFloatArraySetFunc() {
public void setFloatArray(PointerRNA ptr, float[] values)
{
	rna_Object_matrix_local_set.setFloatArray(ptr, values);
}};

public static PropFloatArrayGetFunc Object_matrix_basis_get = new PropFloatArrayGetFunc() {
public void getFloatArray(PointerRNA ptr, float[] values)
{
	rna_Object_matrix_basis_get.getFloatArray(ptr, values);
}};

public static PropFloatArraySetFunc Object_matrix_basis_set = new PropFloatArraySetFunc() {
public void setFloatArray(PointerRNA ptr, float[] values)
{
	rna_Object_matrix_basis_set.setFloatArray(ptr, values);
}};

private static PropCollectionEndFunc Object_constraints_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
}};

private static PropCollectionEndFunc Object_modifiers_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
}};

private static PropPointerGetFunc Object_game_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_Object_game_settings_get.getPtr(ptr);
}};

private static PropCollectionEndFunc Object_vertex_groups_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
}};

private static PropPointerGetFunc Object_field_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_Object_field_get.getPtr(ptr);
}};

private static PropPointerGetFunc Object_collision_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_Object_collision_get.getPtr(ptr);
}};

private static PropCollectionEndFunc Object_particle_systems_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
}};

private static PropPointerSetFunc Object_dupli_group_set = new PropPointerSetFunc() {
public void setPtr(PointerRNA ptr, PointerRNA value)
{
	rna_Object_dup_group_set.setPtr(ptr, value);
}};

private static PropCollectionEndFunc Object_dupli_list_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
}};

private static PropPointerGetFunc Object_active_shape_key_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_Object_active_shape_key_get.getPtr(ptr);
}};

public int getActive_shape_key_index() { return Object_active_shape_key_index_get.getInt(ptr); }
private static PropIntGetFunc Object_active_shape_key_index_get = new PropIntGetFunc() {
public int getInt(PointerRNA ptr)
{
	return rna_Object_active_shape_key_index_get.getInt(ptr);
}};

public void setActive_shape_key_index(int value) { Object_active_shape_key_index_set.setInt(ptr, value); }
private static PropIntSetFunc Object_active_shape_key_index_set = new PropIntSetFunc() {
public void setInt(PointerRNA ptr, int value)
{
	rna_Object_active_shape_key_index_set.setInt(ptr, value);
}};

/* Object */
private static CollectionPropertyRNA rna_Object_rna_properties = new CollectionPropertyRNA(
	null, null,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	Object_rna_properties_begin, Object_rna_properties_next, Object_rna_properties_end, Object_rna_properties_get, null, null, rna_builtin_properties_lookup_string, RnaProperty.RNA_Property
);

private static PointerPropertyRNA rna_Object_rna_type = new PointerPropertyRNA(
	null, null,
	-1, "rna_type", 524288, "RNA",
	"RNA type definition",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	Object_rna_type_get, null, null, null,RnaStruct.RNA_Struct
);

private static PointerPropertyRNA rna_Object_data = new PointerPropertyRNA(
	null, null,
	-1, "data", 1, "Data",
	"Object data",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update_data, 0, rna_Object_data_editable, null,
	0, -1, null,
	null, Object_data_set, rna_Object_data_typef, null,RNA_ID
);

private static EnumPropertyItem[] rna_Object_type_items = {
	new EnumPropertyItem(1, "MESH", 0, "Mesh", ""),
	new EnumPropertyItem(2, "CURVE", 0, "Curve", ""),
	new EnumPropertyItem(3, "SURFACE", 0, "Surface", ""),
	new EnumPropertyItem(5, "META", 0, "Meta", ""),
	new EnumPropertyItem(4, "FONT", 0, "Font", ""),
	new EnumPropertyItem(0, "", 0, null, null),
	new EnumPropertyItem(25, "ARMATURE", 0, "Armature", ""),
	new EnumPropertyItem(22, "LATTICE", 0, "Lattice", ""),
	new EnumPropertyItem(0, "EMPTY", 0, "Empty", ""),
	new EnumPropertyItem(0, "", 0, null, null),
	new EnumPropertyItem(11, "CAMERA", 0, "Camera", ""),
	new EnumPropertyItem(10, "LAMP", 0, "Lamp", ""),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_Object_type = new EnumPropertyRNA(
	null, null,
	-1, "type", 2, "Type",
	"Type of Object",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, rna_Object_type_items, 12, 0
);

private static EnumPropertyItem[] rna_Object_mode_items = {
	new EnumPropertyItem(0, "OBJECT", 130, "Object", ""),
	new EnumPropertyItem(1, "EDIT", 131, "Edit", ""),
	new EnumPropertyItem(2, "SCULPT", 136, "Sculpt", ""),
	new EnumPropertyItem(4, "VERTEX_PAINT", 133, "Vertex Paint", ""),
	new EnumPropertyItem(8, "WEIGHT_PAINT", 135, "Weight Paint", ""),
	new EnumPropertyItem(16, "TEXTURE_PAINT", 134, "Texture Paint", ""),
	new EnumPropertyItem(32, "PARTICLE_EDIT", 138, "Particle Edit", ""),
	new EnumPropertyItem(64, "POSE", 137, "Pose", ""),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_Object_mode = new EnumPropertyRNA(
	null, null,
	-1, "mode", 2, "Mode",
	"Object interaction mode",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, rna_Object_mode_items, 8, 0
);

private static BooleanPropertyRNA rna_Object_layers = new BooleanPropertyRNA(
	null, null,
	-1, "layers", 65539, "Layers",
	"Layers the object is on",
	0,
	PROP_BOOLEAN, PROP_LAYER_MEMBER|PROP_UNIT_NONE, null, 0, new int[]{20, 0, 0}, 0,
	rna_Object_layer_update, 85327872, null, null,
	0, -1, null,
	null, null, null, rna_Object_layer_set, false, null
);

private static BooleanPropertyRNA rna_Object_select = new BooleanPropertyRNA(
	null, null,
	-1, "select", 3, "Select",
	"Object selection state",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_select_update, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

static float[] rna_Object_bound_box_default = {
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f
};

private static FloatPropertyRNA rna_Object_bound_box = new FloatPropertyRNA(
	null, null,
	-1, "bound_box", 2, "Bound Box",
	"Objects bound box in object-space coordinates, all values are -1.0 when not available.",
	0,
	PROP_FLOAT, PROP_NONE|PROP_UNIT_NONE, null, 2, new int[]{8, 3, 0}, 24,
	null, 0, null, null,
	0, -1, null,
	null, null, Object_bound_box_get, null, null, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, rna_Object_bound_box_default
);

private static PointerPropertyRNA rna_Object_parent = new PointerPropertyRNA(
	null, null,
	-1, "parent", 1048577, "Parent",
	"Parent Object",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_dependency_update, 85327872, null, null,
	0, -1, null,
	null, Object_parent_set, null, null,null
);

private static EnumPropertyItem[] rna_Object_parent_type_items = {
	new EnumPropertyItem(0, "OBJECT", 0, "Object", ""),
	new EnumPropertyItem(1, "CURVE", 0, "Curve", ""),
	new EnumPropertyItem(2, "KEY", 0, "Key", ""),
	new EnumPropertyItem(4, "ARMATURE", 0, "Armature", ""),
	new EnumPropertyItem(4, "LATTICE", 0, "Lattice", ""),
	new EnumPropertyItem(5, "VERTEX", 0, "Vertex", ""),
	new EnumPropertyItem(6, "VERTEX_3", 0, "3 Vertices", ""),
	new EnumPropertyItem(7, "BONE", 0, "Bone", ""),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_Object_parent_type = new EnumPropertyRNA(
	null, null,
	-1, "parent_type", 3, "Parent Type",
	"Type of parent relation",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_dependency_update, 85327872, null, null,
	0, -1, null,
	null, Object_parent_type_set, rna_Object_parent_type_itemf, rna_Object_parent_type_items, 8, 0
);

private static IntPropertyRNA rna_Object_parent_vertices = new IntPropertyRNA(
	null, null,
	-1, "parent_vertices", 2, "Parent Vertices",
	"Indices of vertices in cases of a vertex parenting relation",
	0,
	PROP_INT, PROP_UNSIGNED|PROP_UNIT_NONE, null, 0, new int[]{3, 0, 0}, 0,
	rna_Object_internal_update, 85327872, null, null,
	0, -1, null,
	null, null, null, null, null,
	0, 10000, 0, INT_MAX, 1, 0, null
);

private static StringPropertyRNA rna_Object_parent_bone = new StringPropertyRNA(
	null, null,
	-1, "parent_bone", 1, "Parent Bone",
	"Name of parent bone in case of a bone parenting relation",
	0,
	PROP_STRING, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_dependency_update, 85327872, null, null,
	0, -1, null,
	null, null, Object_parent_bone_set, 0, ""
);

private static EnumPropertyItem[] rna_Object_track_axis_items = {
	new EnumPropertyItem(0, "POS_X", 0, "+X", ""),
	new EnumPropertyItem(1, "POS_Y", 0, "+Y", ""),
	new EnumPropertyItem(2, "POS_Z", 0, "+Z", ""),
	new EnumPropertyItem(3, "NEG_X", 0, "-X", ""),
	new EnumPropertyItem(4, "NEG_Y", 0, "-Y", ""),
	new EnumPropertyItem(5, "NEG_Z", 0, "-Z", ""),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_Object_track_axis = new EnumPropertyRNA(
	null, null,
	-1, "track_axis", 3, "Track Axis",
	"Axis that points in \'forward\' direction",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 85327872, null, null,
	0, -1, null,
	null, null, null, rna_Object_track_axis_items, 6, 0
);

private static EnumPropertyItem[] rna_Object_up_axis_items = {
	new EnumPropertyItem(0, "X", 0, "X", ""),
	new EnumPropertyItem(1, "Y", 0, "Y", ""),
	new EnumPropertyItem(2, "Z", 0, "Z", ""),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_Object_up_axis = new EnumPropertyRNA(
	null, null,
	-1, "up_axis", 3, "Up Axis",
	"Axis that points in the upward direction",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 85327872, null, null,
	0, -1, null,
	null, null, null, rna_Object_up_axis_items, 3, 0
);

private static PointerPropertyRNA rna_Object_proxy = new PointerPropertyRNA(
	null, null,
	-1, "proxy", 0, "Proxy",
	"Library object this proxy object controls",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, null,null
);

private static PointerPropertyRNA rna_Object_proxy_group = new PointerPropertyRNA(
	null, null,
	-1, "proxy_group", 0, "Proxy Group",
	"Library group duplicator object this proxy object controls",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, null,null
);

private static CollectionPropertyRNA rna_Object_material_slots = new CollectionPropertyRNA(
	null, null,
	-1, "material_slots", 0, "Material Slots",
	"Material slots in the object",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, Object_material_slots_end, Object_material_slots_get, null, null, null, RNA_MaterialSlot
);

private static PointerPropertyRNA rna_Object_active_material = new PointerPropertyRNA(
	null, null,
	-1, "active_material", 1, "Active Material",
	"Active material being displayed",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_MaterialSlot_update, 85327872, null, null,
	0, -1, null,
	Object_active_material_get, Object_active_material_set, null, null,RNA_Material
);

private static IntPropertyRNA rna_Object_active_material_index = new IntPropertyRNA(
	null, null,
	-1, "active_material_index", 1, "Active Material Index",
	"Index of active material slot",
	0,
	PROP_INT, PROP_UNSIGNED|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 102629376, null, null,
	0, -1, null,
	Object_active_material_index_get, Object_active_material_index_set, null, null, rna_Object_active_material_index_range,
	0, 10000, 0, INT_MAX, 1, 0, null
);

private static FloatPropertyRNA rna_Object_location = new FloatPropertyRNA(
	null, null,
	-1, "location", 3, "Location",
	"Location of the object",
	0,
	PROP_FLOAT, PROP_TRANSLATION|PROP_UNIT_LENGTH, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, rna_Object_location_editable,
	0, -1, null,
	null, null, null, null, null, -FLT_MAX, FLT_MAX, -FLT_MAX, FLT_MAX, 1.0f, 3, 0.0f, null
);

private static FloatPropertyRNA rna_Object_rotation_quaternion = new FloatPropertyRNA(
	null, null,
	-1, "rotation_quaternion", 3, "Quaternion Rotation",
	"Rotation in Quaternions",
	0,
	PROP_FLOAT, PROP_QUATERNION|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, rna_Object_rotation_4d_editable,
	0, -1, null,
	null, null, null, null, null, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, null
);

private static FloatPropertyRNA rna_Object_rotation_axis_angle = new FloatPropertyRNA(
	null, null,
	-1, "rotation_axis_angle", 3, "Axis-Angle Rotation",
	"Angle of Rotation for Axis-Angle rotation representation",
	0,
	PROP_FLOAT, PROP_AXISANGLE|PROP_UNIT_NONE, null, 0, new int[]{4, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, rna_Object_rotation_4d_editable,
	0, -1, null,
	null, null, rna_Object_rotation_axis_angle_get, rna_Object_rotation_axis_angle_set, null, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, null
);

private static FloatPropertyRNA rna_Object_rotation_euler = new FloatPropertyRNA(
	null, null,
	-1, "rotation_euler", 3, "Euler Rotation",
	"Rotation in Eulers",
	0,
	PROP_FLOAT, PROP_EULER|PROP_UNIT_ROTATION, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, rna_Object_rotation_euler_editable,
	0, -1, null,
	null, null, null, null, null, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, null
);

private static EnumPropertyItem[] rna_Object_rotation_mode_items = {
	new EnumPropertyItem(0, "QUATERNION", 0, "Quaternion (WXYZ)", "No Gimbal Lock"),
	new EnumPropertyItem(1, "XYZ", 0, "XYZ Euler", "XYZ Rotation Order. Prone to Gimbal Lock. (Default)"),
	new EnumPropertyItem(2, "XZY", 0, "XZY Euler", "XZY Rotation Order. Prone to Gimbal Lock"),
	new EnumPropertyItem(3, "YXZ", 0, "YXZ Euler", "YXZ Rotation Order. Prone to Gimbal Lock"),
	new EnumPropertyItem(4, "YZX", 0, "YZX Euler", "YZX Rotation Order. Prone to Gimbal Lock"),
	new EnumPropertyItem(5, "ZXY", 0, "ZXY Euler", "ZXY Rotation Order. Prone to Gimbal Lock"),
	new EnumPropertyItem(6, "ZYX", 0, "ZYX Euler", "ZYX Rotation Order. Prone to Gimbal Lock"),
	new EnumPropertyItem(-1, "AXIS_ANGLE", 0, "Axis Angle", "Axis Angle (W+XYZ). Defines a rotation around some axis defined by 3D-Vector"),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_Object_rotation_mode = new EnumPropertyRNA(
	null, null,
	-1, "rotation_mode", 3, "Rotation Mode",
	"",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, Object_rotation_mode_set, null, rna_Object_rotation_mode_items, 8, 0
);

private static FloatPropertyRNA rna_Object_scale = new FloatPropertyRNA(
	null, null,
	-1, "scale", 3, "Scale",
	"Scaling of the object",
	0,
	PROP_FLOAT, PROP_XYZ|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, rna_Object_scale_editable,
	0, -1, null,
	null, null, null, null, null, -FLT_MAX, FLT_MAX, -FLT_MAX, FLT_MAX, 1.0f, 3, 0.0f, null
);

private static FloatPropertyRNA rna_Object_dimensions = new FloatPropertyRNA(
	null, null,
	-1, "dimensions", 3, "Dimensions",
	"Absolute bounding box dimensions of the object",
	0,
	PROP_FLOAT, PROP_XYZ|PROP_UNIT_LENGTH, null, 0, new int[]{3, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, rna_Object_dimensions_get, rna_Object_dimensions_set, null, -FLT_MAX, FLT_MAX, -FLT_MAX, FLT_MAX, 1.0f, 3, 0.0f, null
);

private static FloatPropertyRNA rna_Object_delta_location = new FloatPropertyRNA(
	null, null,
	-1, "delta_location", 3, "Delta Location",
	"Extra translation added to the location of the object",
	0,
	PROP_FLOAT, PROP_TRANSLATION|PROP_UNIT_LENGTH, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, null, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, null
);

private static FloatPropertyRNA rna_Object_delta_rotation_euler = new FloatPropertyRNA(
	null, null,
	-1, "delta_rotation_euler", 3, "Delta Rotation (Euler)",
	"Extra rotation added to the rotation of the object (when using Euler rotations)",
	0,
	PROP_FLOAT, PROP_EULER|PROP_UNIT_ROTATION, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, null, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, null
);

private static FloatPropertyRNA rna_Object_delta_rotation_quaternion = new FloatPropertyRNA(
	null, null,
	-1, "delta_rotation_quaternion", 3, "Delta Rotation (Quaternion)",
	"Extra rotation added to the rotation of the object (when using Quaternion rotations)",
	0,
	PROP_FLOAT, PROP_QUATERNION|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, null, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, null
);

private static FloatPropertyRNA rna_Object_delta_scale = new FloatPropertyRNA(
	null, null,
	-1, "delta_scale", 3, "Delta Scale",
	"Extra scaling added to the scale of the object",
	0,
	PROP_FLOAT, PROP_XYZ|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, null, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, null
);

private static BooleanPropertyRNA rna_Object_lock_location = new BooleanPropertyRNA(
	null, null,
	-1, "lock_location", 4099, "Lock Location",
	"Lock editing of location in the interface",
	40,
	PROP_BOOLEAN, PROP_XYZ|PROP_UNIT_NONE, null, 0, new int[]{3, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_lock_rotation = new BooleanPropertyRNA(
	null, null,
	-1, "lock_rotation", 4099, "Lock Rotation",
	"Lock editing of rotation in the interface",
	40,
	PROP_BOOLEAN, PROP_XYZ|PROP_UNIT_NONE, null, 0, new int[]{3, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_lock_rotation_w = new BooleanPropertyRNA(
	null, null,
	-1, "lock_rotation_w", 4099, "Lock Rotation (4D Angle)",
	"Lock editing of \'angle\' component of four-component rotations in the interface",
	40,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_lock_rotations_4d = new BooleanPropertyRNA(
	null, null,
	-1, "lock_rotations_4d", 3, "Lock Rotations (4D)",
	"Lock editing of four component rotations by components (instead of as Eulers)",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_lock_scale = new BooleanPropertyRNA(
	null, null,
	-1, "lock_scale", 4099, "Lock Scale",
	"Lock editing of scale in the interface",
	40,
	PROP_BOOLEAN, PROP_XYZ|PROP_UNIT_NONE, null, 0, new int[]{3, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

static float[] rna_Object_matrix_world_default = {
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f
};

private static FloatPropertyRNA rna_Object_matrix_world = new FloatPropertyRNA(
	null, null,
	-1, "matrix_world", 1, "Matrix World",
	"Worldspace transformation matrix",
	0,
	PROP_FLOAT, PROP_MATRIX|PROP_UNIT_NONE, null, 2, new int[]{4, 4, 0}, 16,
	rna_Object_matrix_world_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, null, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, rna_Object_matrix_world_default
);

static float[] rna_Object_matrix_local_default = {
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f
};

private static FloatPropertyRNA rna_Object_matrix_local = new FloatPropertyRNA(
	null, null,
	-1, "matrix_local", 1, "Local Matrix",
	"Parent relative transformation matrix",
	0,
	PROP_FLOAT, PROP_MATRIX|PROP_UNIT_NONE, null, 2, new int[]{4, 4, 0}, 16,
	null, 84934656, null, null,
	0, -1, null,
	null, null, Object_matrix_local_get, Object_matrix_local_set, null, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, rna_Object_matrix_local_default
);

static float[] rna_Object_matrix_basis_default = {
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f,
	0.0f
};

private static FloatPropertyRNA rna_Object_matrix_basis = new FloatPropertyRNA(
	null, null,
	-1, "matrix_basis", 1, "Input Matrix",
	"Matrix access to location, rotation and scale (including deltas), before constraints and parenting are applied.",
	0,
	PROP_FLOAT, PROP_MATRIX|PROP_UNIT_NONE, null, 2, new int[]{4, 4, 0}, 16,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, Object_matrix_basis_get, Object_matrix_basis_set, null, -10000.0f, 10000.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, rna_Object_matrix_basis_default
);

private static CollectionPropertyRNA rna_Object_constraints = new CollectionPropertyRNA(
	null, null,
	-1, "constraints", 0, "Constraints",
	"Constraints affecting the transformation of the object",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, Object_constraints_end, null, null, null, null, RNA_Constraint
);

private static CollectionPropertyRNA rna_Object_modifiers = new CollectionPropertyRNA(
	null, null,
	-1, "modifiers", 0, "Modifiers",
	"Modifiers affecting the geometric data of the object",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, Object_modifiers_end, null, null, null, null, RNA_Modifier
);

private static PointerPropertyRNA rna_Object_game = new PointerPropertyRNA(
	null, null,
	-1, "game", 262144, "Game Settings",
	"Game engine related settings for the object",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	Object_game_get, null, null, null,RNA_GameObjectSettings
);

private static CollectionPropertyRNA rna_Object_vertex_groups = new CollectionPropertyRNA(
	null, null,
	-1, "vertex_groups", 0, "Vertex Groups",
	"Vertex groups of the object",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, RNA_VertexGroup,
	null, null, Object_vertex_groups_end, null, null, null, null, RNA_VertexGroup
);

private static EnumPropertyItem[] rna_Object_empty_draw_type_items = {
	new EnumPropertyItem(1, "ARROWS", 0, "Arrows", ""),
	new EnumPropertyItem(4, "SINGLE_ARROW", 0, "Single Arrow", ""),
	new EnumPropertyItem(2, "PLAIN_AXES", 0, "Plain Axes", ""),
	new EnumPropertyItem(3, "CIRCLE", 0, "Circle", ""),
	new EnumPropertyItem(5, "CUBE", 0, "Cube", ""),
	new EnumPropertyItem(6, "SPHERE", 0, "Sphere", ""),
	new EnumPropertyItem(7, "CONE", 0, "Cone", ""),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_Object_empty_draw_type = new EnumPropertyRNA(
	null, null,
	-1, "empty_draw_type", 3, "Empty Display Type",
	"Viewport display style for empties",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, rna_Object_empty_draw_type_items, 7, 1
);

private static FloatPropertyRNA rna_Object_empty_draw_size = new FloatPropertyRNA(
	null, null,
	-1, "empty_draw_size", 3, "Empty Display Size",
	"Size of display for empties in the viewport",
	0,
	PROP_FLOAT, PROP_DISTANCE|PROP_UNIT_LENGTH, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, null, 0.0099999998f, 100.0f, 0.0001000000f, 1000.0f, 1.0f, 2, 0.0f, null
);

private static IntPropertyRNA rna_Object_pass_index = new IntPropertyRNA(
	null, null,
	-1, "pass_index", 3, "Pass Index",
	"Index # for the IndexOB render pass",
	0,
	PROP_INT, PROP_UNSIGNED|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 83886080, null, null,
	0, -1, null,
	null, null, null, null, null,
	0, 10000, 0, INT_MAX, 1, 0, null
);

private static FloatPropertyRNA rna_Object_color = new FloatPropertyRNA(
	null, null,
	-1, "color", 3, "Color",
	"Object color and alpha, used when faces have the ObColor mode enabled",
	0,
	PROP_FLOAT, PROP_COLOR|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, null, 0.0f, 1.0f, -FLT_MAX, FLT_MAX, 10.0f, 3, 0.0f, null
);

private static PointerPropertyRNA rna_Object_field = new PointerPropertyRNA(
	null, null,
	-1, "field", 0, "Field Settings",
	"Settings for using the objects as a field in physics simulation",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	Object_field_get, null, null, null,RNA_FieldSettings
);

private static PointerPropertyRNA rna_Object_collision = new PointerPropertyRNA(
	null, null,
	-1, "collision", 0, "Collision Settings",
	"Settings for using the objects as a collider in physics simulation",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	Object_collision_get, null, null, null,RNA_CollisionSettings
);

private static PointerPropertyRNA rna_Object_soft_body = new PointerPropertyRNA(
	null, null,
	-1, "soft_body", 0, "Soft Body Settings",
	"Settings for soft body simulation",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, null,RNA_SoftBodySettings
);

private static CollectionPropertyRNA rna_Object_particle_systems = new CollectionPropertyRNA(
	null, null,
	-1, "particle_systems", 0, "Particle Systems",
	"Particle systems emitted from the object",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, Object_particle_systems_end, null, null, null, null, RNA_ParticleSystem
);

private static BooleanPropertyRNA rna_Object_hide = new BooleanPropertyRNA(
	null, null,
	-1, "hide", 4099, "Restrict View",
	"Restrict visibility in the viewport",
	253,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_hide_select = new BooleanPropertyRNA(
	null, null,
	-1, "hide_select", 4099, "Restrict Select",
	"Restrict selection in the viewport",
	255,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_hide_render = new BooleanPropertyRNA(
	null, null,
	-1, "hide_render", 4099, "Restrict Render",
	"Restrict renderability",
	257,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_use_slow_parent = new BooleanPropertyRNA(
	null, null,
	-1, "use_slow_parent", 3, "Slow Parent",
	"Create a delay in the parent relationship",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static EnumPropertyItem[] rna_Object_dupli_type_items = {
	new EnumPropertyItem(0, "NONE", 0, "None", ""),
	new EnumPropertyItem(8, "FRAMES", 0, "Frames", "Make copy of object for every frame"),
	new EnumPropertyItem(16, "VERTS", 0, "Verts", "Duplicate child objects on all vertices"),
	new EnumPropertyItem(512, "FACES", 0, "Faces", "Duplicate child objects on all faces"),
	new EnumPropertyItem(256, "GROUP", 0, "Group", "Enable group instancing"),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_Object_dupli_type = new EnumPropertyRNA(
	null, null,
	-1, "dupli_type", 3, "Dupli Type",
	"If not None, object duplication method to use",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_dependency_update, 85327872, null, null,
	0, -1, null,
	null, null, null, rna_Object_dupli_type_items, 5, 0
);

private static BooleanPropertyRNA rna_Object_use_dupli_frames_speed = new BooleanPropertyRNA(
	null, null,
	-1, "use_dupli_frames_speed", 3, "Dupli Frames Speed",
	"Set dupliframes to use the frame",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_use_dupli_vertices_rotation = new BooleanPropertyRNA(
	null, null,
	-1, "use_dupli_vertices_rotation", 3, "Dupli Verts Rotation",
	"Rotate dupli according to vertex normal",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_use_dupli_faces_scale = new BooleanPropertyRNA(
	null, null,
	-1, "use_dupli_faces_scale", 3, "Dupli Faces Inherit Scale",
	"Scale dupli based on face size",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static FloatPropertyRNA rna_Object_dupli_faces_scale = new FloatPropertyRNA(
	null, null,
	-1, "dupli_faces_scale", 3, "Dupli Faces Scale",
	"Scale the DupliFace objects",
	0,
	PROP_FLOAT, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, null, 0.0010000000f, 10000.0f, 0.0010000000f, 10000.0f, 10.0f, 3, 0.0f, null
);

private static PointerPropertyRNA rna_Object_dupli_group = new PointerPropertyRNA(
	null, null,
	-1, "dupli_group", 1, "Dupli Group",
	"Instance an existing group",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_dependency_update, 85327872, null, null,
	0, -1, null,
	null, Object_dupli_group_set, null, null,null
);

private static IntPropertyRNA rna_Object_dupli_frames_start = new IntPropertyRNA(
	null, null,
	-1, "dupli_frames_start", 3, "Dupli Frames Start",
	"Start frame for DupliFrames",
	0,
	PROP_INT, PROP_NONE|PROP_UNIT_TIME, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 85327872, null, null,
	0, -1, null,
	null, null, null, null, null,
	-300000, 300000, -300000, 300000, 1, 0, null
);

private static IntPropertyRNA rna_Object_dupli_frames_end = new IntPropertyRNA(
	null, null,
	-1, "dupli_frames_end", 3, "Dupli Frames End",
	"End frame for DupliFrames",
	0,
	PROP_INT, PROP_NONE|PROP_UNIT_TIME, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 85327872, null, null,
	0, -1, null,
	null, null, null, null, null,
	-300000, 300000, -300000, 300000, 1, 0, null
);

private static IntPropertyRNA rna_Object_dupli_frames_on = new IntPropertyRNA(
	null, null,
	-1, "dupli_frames_on", 3, "Dupli Frames On",
	"Number of frames to use between DupOff frames",
	0,
	PROP_INT, PROP_NONE|PROP_UNIT_TIME, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 85327872, null, null,
	0, -1, null,
	null, null, null, null, null,
	1, 1500, 1, 300000, 1, 0, null
);

private static IntPropertyRNA rna_Object_dupli_frames_off = new IntPropertyRNA(
	null, null,
	-1, "dupli_frames_off", 3, "Dupli Frames Off",
	"Recurring frames to exclude from the Dupliframes",
	0,
	PROP_INT, PROP_NONE|PROP_UNIT_TIME, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 85327872, null, null,
	0, -1, null,
	null, null, null, null, null,
	0, 1500, 0, 300000, 1, 0, null
);

private static CollectionPropertyRNA rna_Object_dupli_list = new CollectionPropertyRNA(
	null, null,
	-1, "dupli_list", 0, "Dupli list",
	"Object duplis",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, Object_dupli_list_end, null, null, null, null, RNA_DupliObject
);

private static BooleanPropertyRNA rna_Object_is_duplicator = new BooleanPropertyRNA(
	null, null,
	-1, "is_duplicator", 2, "is_duplicator",
	"",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static FloatPropertyRNA rna_Object_time_offset = new FloatPropertyRNA(
	null, null,
	-1, "time_offset", 3, "Time Offset",
	"Animation offset in frames for F-Curve and dupligroup instances",
	0,
	PROP_FLOAT, PROP_NONE|PROP_UNIT_TIME, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, null, -300000.0f, 300000.0f, -300000.0f, 300000.0f, 10.0f, 3, 0.0f, null
);

private static BooleanPropertyRNA rna_Object_use_time_offset_edit = new BooleanPropertyRNA(
	null, null,
	-1, "use_time_offset_edit", 3, "Time Offset Edit",
	"Use time offset when inserting keys and display time offset for F-Curve and action views",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_use_time_offset_parent = new BooleanPropertyRNA(
	null, null,
	-1, "use_time_offset_parent", 3, "Time Offset Parent",
	"Apply the time offset to this objects parent relationship",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_use_time_offset_particle = new BooleanPropertyRNA(
	null, null,
	-1, "use_time_offset_particle", 3, "Time Offset Particle",
	"Let the time offset work on the particle effect",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_use_time_offset_add_parent = new BooleanPropertyRNA(
	null, null,
	-1, "use_time_offset_add_parent", 3, "Time Offset Add Parent",
	"Add the parents time offset value",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update, 84934656, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static EnumPropertyItem[] rna_Object_draw_type_items = {
	new EnumPropertyItem(1, "BOUNDS", 0, "Bounds", ""),
	new EnumPropertyItem(2, "WIRE", 0, "Wire", ""),
	new EnumPropertyItem(3, "SOLID", 0, "Solid", ""),
	new EnumPropertyItem(5, "TEXTURED", 0, "Textured", ""),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_Object_draw_type = new EnumPropertyRNA(
	null, null,
	-1, "draw_type", 3, "Maximum Draw Type",
	"Maximum draw type to display object with in viewport",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, rna_Object_draw_type_items, 4, 1
);

private static BooleanPropertyRNA rna_Object_show_bounds = new BooleanPropertyRNA(
	null, null,
	-1, "show_bounds", 3, "Draw Bounds",
	"Displays the object\'s bounds",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static EnumPropertyItem[] rna_Object_draw_bounds_type_items = {
	new EnumPropertyItem(0, "BOX", 0, "Box", ""),
	new EnumPropertyItem(1, "SPHERE", 0, "Sphere", ""),
	new EnumPropertyItem(2, "CYLINDER", 0, "Cylinder", ""),
	new EnumPropertyItem(3, "CONE", 0, "Cone", ""),
	new EnumPropertyItem(4, "POLYHEDRON", 0, "Polyhedron", ""),
	new EnumPropertyItem(7, "CAPSULE", 0, "Capsule", ""),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_Object_draw_bounds_type = new EnumPropertyRNA(
	null, null,
	-1, "draw_bounds_type", 3, "Draw Bounds Type",
	"Object boundary display type",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, rna_Object_draw_bounds_type_items, 6, 0
);

private static BooleanPropertyRNA rna_Object_show_name = new BooleanPropertyRNA(
	null, null,
	-1, "show_name", 3, "Draw Name",
	"Displays the object\'s name",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_show_axis = new BooleanPropertyRNA(
	null, null,
	-1, "show_axis", 3, "Draw Axis",
	"Displays the object\'s origin and axis",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_show_texture_space = new BooleanPropertyRNA(
	null, null,
	-1, "show_texture_space", 3, "Draw Texture Space",
	"Displays the object\'s texture space",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_show_wire = new BooleanPropertyRNA(
	null, null,
	-1, "show_wire", 3, "Draw Wire",
	"Adds the object\'s wireframe over solid drawing",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_show_transparent = new BooleanPropertyRNA(
	null, null,
	-1, "show_transparent", 3, "Draw Transparent",
	"Displays material transparency in the object",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_show_x_ray = new BooleanPropertyRNA(
	null, null,
	-1, "show_x_ray", 3, "X-Ray",
	"Makes the object draw in front of others",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 85327872, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static PointerPropertyRNA rna_Object_grease_pencil = new PointerPropertyRNA(
	null, null,
	-1, "grease_pencil", 1, "Grease Pencil Data",
	"Grease Pencil datablock",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, null,RNA_GreasePencil
);

private static PointerPropertyRNA rna_Object_pose_library = new PointerPropertyRNA(
	null, null,
	-1, "pose_library", 0, "Pose Library",
	"Action used as a pose library for armatures",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, null,RNA_Action
);

private static PointerPropertyRNA rna_Object_pose = new PointerPropertyRNA(
	null, null,
	-1, "pose", 0, "Pose",
	"Current pose for armatures",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	null, null, null, null,RNA_Pose
);

private static BooleanPropertyRNA rna_Object_show_only_shape_key = new BooleanPropertyRNA(
	null, null,
	-1, "show_only_shape_key", 4099, "Shape Key Lock",
	"Always show the current Shape for this Object",
	42,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update_data, 0, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_Object_use_shape_key_edit_mode = new BooleanPropertyRNA(
	null, null,
	-1, "use_shape_key_edit_mode", 3, "Shape Key Edit Mode",
	"Apply shape keys in edit mode (for Meshes only)",
	131,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_internal_update_data, 0, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static PointerPropertyRNA rna_Object_active_shape_key = new PointerPropertyRNA(
	null, null,
	-1, "active_shape_key", 0, "Active Shape Key",
	"Current shape key",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	Object_active_shape_key_get, null, null, null,RNA_ShapeKey
);

private static IntPropertyRNA rna_Object_active_shape_key_index = new IntPropertyRNA(
	null, null,
	-1, "active_shape_key_index", 1, "Active Shape Key Index",
	"Current shape key index",
	0,
	PROP_INT, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_Object_active_shape_update, 0, null, null,
	0, -1, null,
	Object_active_shape_key_index_get, Object_active_shape_key_index_set, null, null, rna_Object_active_shape_key_index_range,
	-10000, 10000, INT_MIN, INT_MAX, 1, 0, null
);

static { ListBase tmp = new ListBase();
	ListBaseUtil.BLI_addtail(tmp, rna_Object_rna_properties);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_rna_type);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_data);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_type);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_mode);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_layers);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_select);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_bound_box);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_parent);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_parent_type);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_parent_vertices);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_parent_bone);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_track_axis);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_up_axis);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_proxy);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_proxy_group);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_material_slots);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_active_material);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_active_material_index);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_location);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_rotation_quaternion);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_rotation_axis_angle);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_rotation_euler);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_rotation_mode);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_scale);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_dimensions);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_delta_location);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_delta_rotation_euler);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_delta_rotation_quaternion);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_delta_scale);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_lock_location);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_lock_rotation);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_lock_rotation_w);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_lock_rotations_4d);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_lock_scale);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_matrix_world);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_matrix_local);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_matrix_basis);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_constraints);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_modifiers);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_game);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_vertex_groups);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_empty_draw_type);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_empty_draw_size);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_pass_index);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_color);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_field);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_collision);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_soft_body);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_particle_systems);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_hide);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_hide_select);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_hide_render);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_use_slow_parent);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_dupli_type);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_use_dupli_frames_speed);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_use_dupli_vertices_rotation);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_use_dupli_faces_scale);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_dupli_faces_scale);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_dupli_group);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_dupli_frames_start);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_dupli_frames_end);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_dupli_frames_on);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_dupli_frames_off);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_dupli_list);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_is_duplicator);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_time_offset);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_use_time_offset_edit);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_use_time_offset_parent);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_use_time_offset_particle);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_use_time_offset_add_parent);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_draw_type);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_show_bounds);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_draw_bounds_type);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_show_name);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_show_axis);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_show_texture_space);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_show_wire);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_show_transparent);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_show_x_ray);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_grease_pencil);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_pose_library);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_pose);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_show_only_shape_key);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_use_shape_key_edit_mode);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_active_shape_key);
	ListBaseUtil.BLI_addtail(tmp, rna_Object_active_shape_key_index);
}

static { ListBase tmp = new ListBase();
}

public static StructRNA RNA_Object = new StructRNA(
	RNA_VertexGroup, RnaContext.RNA_Context,
	null,
	rna_Object_rna_properties, rna_Object_active_shape_key_index,
	null,null,
	"Object", 0, "Object", "Object datablock defining an object in a scene",
	159,
	null, rna_Object_rna_properties,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null, null
);

}
