
/* Automatically generated struct definitions for the Data API.
   Do not edit manually, changes will be overwritten.           */

package blender.makesrna.srna;

import blender.makesdna.sdna.*;

import static blender.makesrna.RnaRna.*;
import static blender.makesrna.RnaAccess.*;
import static blender.makesrna.RnaDefine.*;
import static blender.makesrna.RNATypes.*;
import blender.makesrna.rna_internal_types.*;
import blender.blenlib.*;
import blender.blenkernel.*;

import static blender.makesrna.RnaSceneUtil.*;
import static blender.makesrna.RnaSceneApi.*;

public class RnaRenderLayers extends RnaStruct {

/* Autogenerated Functions */

public RnaRenderLayers(PointerRNA ptr) { super(ptr); }

private static PropCollectionGetFunc RenderLayers_rna_properties_get = new PropCollectionGetFunc() {
public PointerRNA get(CollectionPropertyIterator iter)
{
	return rna_builtin_properties_get.get(iter);
}};

private static PropCollectionBeginFunc RenderLayers_rna_properties_begin = new PropCollectionBeginFunc() {
public void begin(CollectionPropertyIterator iter, PointerRNA ptr)
{

	iter.clear();
	iter.parent= ptr;
	iter.prop= (PropertyRNA)rna_RenderLayers_rna_properties;

	rna_builtin_properties_begin.begin(iter, ptr);

	if(iter.valid)
		iter.ptr= RenderLayers_rna_properties_get.get(iter);
}};

private static PropCollectionNextFunc RenderLayers_rna_properties_next = new PropCollectionNextFunc() {
public void next(CollectionPropertyIterator iter)
{
	rna_builtin_properties_next.next(iter);

	if(iter.valid)
		iter.ptr= RenderLayers_rna_properties_get.get(iter);
}};

private static PropCollectionEndFunc RenderLayers_rna_properties_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
	rna_iterator_listbase_end.end(iter);
}};

private static PropPointerGetFunc RenderLayers_rna_type_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_builtin_type_get.getPtr(ptr);
}};

private static PropIntGetFunc RenderLayers_active_index_get = new PropIntGetFunc() {
public int getInt(PointerRNA ptr)
{
	return rna_RenderSettings_active_layer_index_get.getInt(ptr);
}};

private static PropIntSetFunc RenderLayers_active_index_set = new PropIntSetFunc() {
public void setInt(PointerRNA ptr, int value)
{
	rna_RenderSettings_active_layer_index_set.setInt(ptr, value);
}};

public RnaSceneRenderLayer getActive() { return new RnaSceneRenderLayer(RenderLayers_active_get.getPtr(ptr)); }
private static PropPointerGetFunc RenderLayers_active_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_RenderSettings_active_layer_get.getPtr(ptr);
}};

private static PropPointerSetFunc RenderLayers_active_set = new PropPointerSetFunc() {
public void setPtr(PointerRNA ptr, PointerRNA value)
{
	rna_RenderSettings_active_layer_set.setPtr(ptr, value);
}};

/* Render Layers */
private static CollectionPropertyRNA rna_RenderLayers_rna_properties = new CollectionPropertyRNA(
	null, null,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	RenderLayers_rna_properties_begin, RenderLayers_rna_properties_next, RenderLayers_rna_properties_end, RenderLayers_rna_properties_get, null, null, rna_builtin_properties_lookup_string, RnaProperty.RNA_Property
);

private static PointerPropertyRNA rna_RenderLayers_rna_type = new PointerPropertyRNA(
	null, null,
	-1, "rna_type", 524288, "RNA",
	"RNA type definition",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	RenderLayers_rna_type_get, null, null, null,RnaStruct.RNA_Struct
);

private static IntPropertyRNA rna_RenderLayers_active_index = new IntPropertyRNA(
	null, null,
	-1, "active_index", 3, "Active Layer Index",
	"Active index in render layer array",
	0,
	PROP_INT, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	RenderLayers_active_index_get, RenderLayers_active_index_set, null, null, rna_RenderSettings_active_layer_index_range,
	-10000, 10000, INT_MIN, INT_MAX, 1, 0, null
);

private static PointerPropertyRNA rna_RenderLayers_active = new PointerPropertyRNA(
	null, null,
	-1, "active", 1, "Active Render Layer",
	"Active Render Layer",
	0,
	PROP_POINTER, PROP_UNSIGNED|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	RenderLayers_active_get, RenderLayers_active_set, null, null,RnaSceneRenderLayer.RNA_SceneRenderLayer
);

static { ListBase tmp = new ListBase();
	ListBaseUtil.BLI_addtail(tmp, rna_RenderLayers_rna_properties);
	ListBaseUtil.BLI_addtail(tmp, rna_RenderLayers_rna_type);
	ListBaseUtil.BLI_addtail(tmp, rna_RenderLayers_active_index);
	ListBaseUtil.BLI_addtail(tmp, rna_RenderLayers_active);
}

static { ListBase tmp = new ListBase();
}

public static StructRNA RNA_RenderLayers = new StructRNA(
	RnaSceneRenderLayer.RNA_SceneRenderLayer, RnaRenderSettings.RNA_RenderSettings,
	null,
	rna_RenderLayers_rna_properties, rna_RenderLayers_active,
	null,null,
	"RenderLayers", 0, "Render Layers", "Collection of render layers",
	17,
	null, rna_RenderLayers_rna_properties,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null, null
);

}

