//
///* Automatically generated struct definitions for the Data API.
//   Do not edit manually, changes will be overwritten.           */
//
//package blender.makesrna.srna;
//
//import blender.makesdna.sdna.*;
//
//import static blender.makesrna.RnaRna.*;
//import static blender.makesrna.RnaAccess.*;
//import static blender.makesrna.RnaDefine.*;
//import static blender.makesrna.RNATypes.*;
//import blender.makesrna.rna_internal_types.*;
//import blender.blenlib.*;
//import blender.blenkernel.*;
//
//import static blender.makesrna.RnaSceneUtil.*;
//import static blender.makesrna.RnaSceneApi.*;
//
//public class RnaSceneRenderLayer extends RnaStruct {
//
///* Autogenerated Functions */
//
//public RnaSceneRenderLayer(PointerRNA ptr) { super(ptr); }
//
//private static PropCollectionGetFunc SceneRenderLayer_rna_properties_get = new PropCollectionGetFunc() {
//public PointerRNA get(CollectionPropertyIterator iter)
//{
//	return rna_builtin_properties_get.get(iter);
//}};
//
//private static PropCollectionBeginFunc SceneRenderLayer_rna_properties_begin = new PropCollectionBeginFunc() {
//public void begin(CollectionPropertyIterator iter, PointerRNA ptr)
//{
//
//	iter.clear();
//	iter.parent= ptr;
//	iter.prop= (PropertyRNA)rna_SceneRenderLayer_rna_properties;
//
//	rna_builtin_properties_begin.begin(iter, ptr);
//
//	if(iter.valid)
//		iter.ptr= SceneRenderLayer_rna_properties_get.get(iter);
//}};
//
//private static PropCollectionNextFunc SceneRenderLayer_rna_properties_next = new PropCollectionNextFunc() {
//public void next(CollectionPropertyIterator iter)
//{
//	rna_builtin_properties_next.next(iter);
//
//	if(iter.valid)
//		iter.ptr= SceneRenderLayer_rna_properties_get.get(iter);
//}};
//
//private static PropCollectionEndFunc SceneRenderLayer_rna_properties_end = new PropCollectionEndFunc() {
//public void end(CollectionPropertyIterator iter)
//{
//	rna_iterator_listbase_end.end(iter);
//}};
//
//private static PropPointerGetFunc SceneRenderLayer_rna_type_get = new PropPointerGetFunc() {
//public PointerRNA getPtr(PointerRNA ptr)
//{
//	return rna_builtin_type_get.getPtr(ptr);
//}};
//
///* Scene Render Layer */
//private static CollectionPropertyRNA rna_SceneRenderLayer_rna_properties = new CollectionPropertyRNA(
//	null, null,
//	-1, "rna_properties", 128, "Properties",
//	"RNA property collection",
//	0,
//	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
//	null, 0, null, null,
//	0, -1, null,
//	SceneRenderLayer_rna_properties_begin, SceneRenderLayer_rna_properties_next, SceneRenderLayer_rna_properties_end, SceneRenderLayer_rna_properties_get, null, null, rna_builtin_properties_lookup_string, RnaProperty.RNA_Property
//);
//
//private static PointerPropertyRNA rna_SceneRenderLayer_rna_type = new PointerPropertyRNA(
//	null, null,
//	-1, "rna_type", 524288, "RNA",
//	"RNA type definition",
//	0,
//	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
//	null, 0, null, null,
//	0, -1, null,
//	SceneRenderLayer_rna_type_get, null, null, null,RnaStruct.RNA_Struct
//);
//
//static { ListBase tmp = new ListBase();
//	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_rna_properties);
//	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_rna_type);
//}
//
//static { ListBase tmp = new ListBase();
//}
//
//public static StructRNA RNA_SceneRenderLayer = new StructRNA(
//	RnaScreen.RNA_Screen, RnaRenderLayers.RNA_RenderLayers,
//	null,
//	rna_SceneRenderLayer_rna_properties, rna_SceneRenderLayer_rna_type,
//	null,null,
//	"SceneRenderLayer", 0, "Scene Render Layer", "Render layer",
//	157,
//	null, rna_SceneRenderLayer_rna_properties,
//	null,
//	null,
//	null,
//	null,
//	null,
//	null,
//	null,
//	null, null
//);
//
//}


/* Automatically generated struct definitions for the Data API.
   Do not edit manually, changes will be overwritten.           */

package blender.makesrna.srna;

import blender.makesdna.sdna.*;

import static blender.makesrna.RnaRna.*;
import static blender.makesrna.RnaAccess.*;
import static blender.makesrna.RnaDefine.*;
import static blender.makesrna.RNATypes.*;
import blender.makesrna.rna_internal_types.*;
import blender.blenlib.*;
import blender.blenkernel.*;

import static blender.makesrna.RnaSceneUtil.*;
import static blender.makesrna.RnaSceneApi.*;

public class RnaSceneRenderLayer extends RnaStruct {
	
public boolean getUse_zmask() {
	return false;
}

/* Autogenerated Functions */

public RnaSceneRenderLayer(PointerRNA ptr) { super(ptr); }

private static PropCollectionGetFunc SceneRenderLayer_rna_properties_get = new PropCollectionGetFunc() {
public PointerRNA get(CollectionPropertyIterator iter)
{
	return rna_builtin_properties_get.get(iter);
}};

private static PropCollectionBeginFunc SceneRenderLayer_rna_properties_begin = new PropCollectionBeginFunc() {
public void begin(CollectionPropertyIterator iter, PointerRNA ptr)
{

	iter.clear();
	iter.parent= ptr;
	iter.prop= (PropertyRNA)rna_SceneRenderLayer_rna_properties;

	rna_builtin_properties_begin.begin(iter, ptr);

	if(iter.valid)
		iter.ptr= SceneRenderLayer_rna_properties_get.get(iter);
}};

private static PropCollectionNextFunc SceneRenderLayer_rna_properties_next = new PropCollectionNextFunc() {
public void next(CollectionPropertyIterator iter)
{
	rna_builtin_properties_next.next(iter);

	if(iter.valid)
		iter.ptr= SceneRenderLayer_rna_properties_get.get(iter);
}};

private static PropCollectionEndFunc SceneRenderLayer_rna_properties_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
	rna_iterator_listbase_end.end(iter);
}};

private static PropPointerGetFunc SceneRenderLayer_rna_type_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_builtin_type_get.getPtr(ptr);
}};

public void setName(String value) { SceneRenderLayer_name_set.setStr(ptr, StringUtil.toCString(value),0); }
private static PropStringSetFunc SceneRenderLayer_name_set = new PropStringSetFunc() {
public void setStr(PointerRNA ptr, byte[] value, int offset)
{
	rna_SceneRenderLayer_name_set.setStr(ptr, value, offset);
}};

/* Scene Render Layer */
private static CollectionPropertyRNA rna_SceneRenderLayer_rna_properties = new CollectionPropertyRNA(
	null, null,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SceneRenderLayer_rna_properties_begin, SceneRenderLayer_rna_properties_next, SceneRenderLayer_rna_properties_end, SceneRenderLayer_rna_properties_get, null, null, rna_builtin_properties_lookup_string, RnaProperty.RNA_Property
);

private static PointerPropertyRNA rna_SceneRenderLayer_rna_type = new PointerPropertyRNA(
	null, null,
	-1, "rna_type", 524288, "RNA",
	"RNA type definition",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SceneRenderLayer_rna_type_get, null, null, null,RnaStruct.RNA_Struct
);

private static StringPropertyRNA rna_SceneRenderLayer_name = new StringPropertyRNA(
	null, null,
	-1, "name", 1, "Name",
	"Render layer name",
	0,
	PROP_STRING, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, SceneRenderLayer_name_set, 0, ""
);

private static PointerPropertyRNA rna_SceneRenderLayer_material_override = new PointerPropertyRNA(
	null, null,
	-1, "material_override", 1, "Material Override",
	"Material to override all other materials in this render layer",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null,RNA_Material
);

private static PointerPropertyRNA rna_SceneRenderLayer_light_override = new PointerPropertyRNA(
	null, null,
	-1, "light_override", 1, "Light Override",
	"Group to override all other lights in this render layer",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null,RNA_Group
);

private static BooleanPropertyRNA rna_SceneRenderLayer_layers = new BooleanPropertyRNA(
	null, null,
	-1, "layers", 3, "Visible Layers",
	"Scene layers included in this render layer",
	0,
	PROP_BOOLEAN, PROP_LAYER_MEMBER|PROP_UNIT_NONE, null, 0, new int[]{20, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, rna_SceneRenderLayer_layer_set, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_layers_zmask = new BooleanPropertyRNA(
	null, null,
	-1, "layers_zmask", 3, "Zmask Layers",
	"Zmask scene layers",
	0,
	PROP_BOOLEAN, PROP_LAYER|PROP_UNIT_NONE, null, 0, new int[]{20, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use = new BooleanPropertyRNA(
	null, null,
	-1, "use", 3, "Enabled",
	"Disable or enable the render layer",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_zmask = new BooleanPropertyRNA(
	null, null,
	-1, "use_zmask", 3, "Zmask",
	"Only render what\'s in front of the solid z values",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_invert_zmask = new BooleanPropertyRNA(
	null, null,
	-1, "invert_zmask", 3, "Zmask Negate",
	"For Zmask, only render what is behind solid z values instead of in front",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_all_z = new BooleanPropertyRNA(
	null, null,
	-1, "use_all_z", 3, "All Z",
	"Fill in Z values for solid faces in invisible layers, for masking",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_solid = new BooleanPropertyRNA(
	null, null,
	-1, "use_solid", 3, "Solid",
	"Render Solid faces in this Layer",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_halo = new BooleanPropertyRNA(
	null, null,
	-1, "use_halo", 3, "Halo",
	"Render Halos in this Layer (on top of Solid)",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_ztransp = new BooleanPropertyRNA(
	null, null,
	-1, "use_ztransp", 3, "ZTransp",
	"Render Z-Transparent faces in this Layer (On top of Solid and Halos)",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_sky = new BooleanPropertyRNA(
	null, null,
	-1, "use_sky", 3, "Sky",
	"Render Sky in this Layer",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_edge_enhance = new BooleanPropertyRNA(
	null, null,
	-1, "use_edge_enhance", 3, "Edge",
	"Render Edge-enhance in this Layer (only works for Solid faces)",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_strand = new BooleanPropertyRNA(
	null, null,
	-1, "use_strand", 3, "Strand",
	"Render Strands in this Layer",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_combined = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_combined", 3, "Combined",
	"Deliver full combined RGBA buffer",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_z = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_z", 3, "Z",
	"Deliver Z values pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_vector = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_vector", 3, "Vector",
	"Deliver speed vector pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_normal = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_normal", 3, "Normal",
	"Deliver normal pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_uv = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_uv", 3, "UV",
	"Deliver texture UV pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_mist = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_mist", 3, "Mist",
	"Deliver mist factor pass (0.0-1.0)",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_object_index = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_object_index", 3, "Object Index",
	"Deliver object index pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_color = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_color", 3, "Color",
	"Deliver shade-less color pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_diffuse = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_diffuse", 3, "Diffuse",
	"Deliver diffuse pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_specular = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_specular", 3, "Specular",
	"Deliver specular pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_shadow = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_shadow", 3, "Shadow",
	"Deliver shadow pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_ambient_occlusion = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_ambient_occlusion", 3, "AO",
	"Deliver AO pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_reflection = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_reflection", 3, "Reflection",
	"Deliver raytraced reflection pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_refraction = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_refraction", 3, "Refraction",
	"Deliver raytraced refraction pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_emit = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_emit", 3, "Emit",
	"Deliver emission pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_environment = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_environment", 3, "Environment",
	"Deliver environment lighting pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_use_pass_indirect = new BooleanPropertyRNA(
	null, null,
	-1, "use_pass_indirect", 3, "Indirect",
	"Deliver indirect lighting pass",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_exclude_specular = new BooleanPropertyRNA(
	null, null,
	-1, "exclude_specular", 4099, "Specular Exclude",
	"Exclude specular pass from combined",
	257,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_exclude_shadow = new BooleanPropertyRNA(
	null, null,
	-1, "exclude_shadow", 4099, "Shadow Exclude",
	"Exclude shadow pass from combined",
	257,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_exclude_ambient_occlusion = new BooleanPropertyRNA(
	null, null,
	-1, "exclude_ambient_occlusion", 4099, "AO Exclude",
	"Exclude AO pass from combined",
	257,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_exclude_reflection = new BooleanPropertyRNA(
	null, null,
	-1, "exclude_reflection", 4099, "Reflection Exclude",
	"Exclude raytraced reflection pass from combined",
	257,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_exclude_refraction = new BooleanPropertyRNA(
	null, null,
	-1, "exclude_refraction", 4099, "Refraction Exclude",
	"Exclude raytraced refraction pass from combined",
	257,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_exclude_emit = new BooleanPropertyRNA(
	null, null,
	-1, "exclude_emit", 4099, "Emit Exclude",
	"Exclude emission pass from combined",
	257,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_exclude_environment = new BooleanPropertyRNA(
	null, null,
	-1, "exclude_environment", 4099, "Environment Exclude",
	"Exclude environment pass from combined",
	257,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

private static BooleanPropertyRNA rna_SceneRenderLayer_exclude_indirect = new BooleanPropertyRNA(
	null, null,
	-1, "exclude_indirect", 4099, "Indirect Exclude",
	"Exclude indirect pass from combined",
	257,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SceneRenderLayer_pass_update, 67371008, null, null,
	0, -1, null,
	null, null, null, null, false, null
);

static { ListBase tmp = new ListBase();
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_rna_properties);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_rna_type);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_name);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_material_override);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_light_override);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_layers);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_layers_zmask);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_zmask);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_invert_zmask);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_all_z);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_solid);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_halo);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_ztransp);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_sky);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_edge_enhance);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_strand);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_combined);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_z);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_vector);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_normal);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_uv);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_mist);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_object_index);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_color);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_diffuse);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_specular);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_shadow);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_ambient_occlusion);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_reflection);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_refraction);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_emit);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_environment);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_use_pass_indirect);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_exclude_specular);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_exclude_shadow);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_exclude_ambient_occlusion);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_exclude_reflection);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_exclude_refraction);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_exclude_emit);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_exclude_environment);
	ListBaseUtil.BLI_addtail(tmp, rna_SceneRenderLayer_exclude_indirect);
}

static { ListBase tmp = new ListBase();
}

public static StructRNA RNA_SceneRenderLayer = new StructRNA(
	RnaScreen.RNA_Screen, RnaRenderLayers.RNA_RenderLayers,
	null,
	rna_SceneRenderLayer_rna_properties, rna_SceneRenderLayer_exclude_indirect,
	null,null,
	"SceneRenderLayer", 0, "Scene Render Layer", "Render layer",
	157,
	rna_SceneRenderLayer_name, rna_SceneRenderLayer_rna_properties,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null, null
);

}

