
/* Automatically generated struct definitions for the Data API.
   Do not edit manually, changes will be overwritten.           */

package blender.makesrna.srna;

import blender.makesdna.sdna.*;

import static blender.makesrna.RnaRna.*;
import static blender.makesrna.RnaAccess.*;
import static blender.makesrna.RnaDefine.*;
import static blender.makesrna.RNATypes.*;
import blender.makesrna.rna_internal_types.*;
import blender.blenlib.*;
import blender.blenkernel.*;

import static blender.makesrna.RnaSpaceUtil.*;

public class RnaSpaceNodeEditor extends RnaSpace {

/* Autogenerated Functions */

public RnaSpaceNodeEditor(PointerRNA ptr) { super(ptr); }

private static PropCollectionGetFunc SpaceNodeEditor_rna_properties_get = new PropCollectionGetFunc() {
public PointerRNA get(CollectionPropertyIterator iter)
{
	return rna_builtin_properties_get.get(iter);
}};

private static PropCollectionBeginFunc SpaceNodeEditor_rna_properties_begin = new PropCollectionBeginFunc() {
public void begin(CollectionPropertyIterator iter, PointerRNA ptr)
{

	iter.clear();
	iter.parent= ptr;
	iter.prop= (PropertyRNA)rna_SpaceNodeEditor_rna_properties;

	rna_builtin_properties_begin.begin(iter, ptr);

	if(iter.valid)
		iter.ptr= SpaceNodeEditor_rna_properties_get.get(iter);
}};

private static PropCollectionNextFunc SpaceNodeEditor_rna_properties_next = new PropCollectionNextFunc() {
public void next(CollectionPropertyIterator iter)
{
	rna_builtin_properties_next.next(iter);

	if(iter.valid)
		iter.ptr= SpaceNodeEditor_rna_properties_get.get(iter);
}};

private static PropCollectionEndFunc SpaceNodeEditor_rna_properties_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
	rna_iterator_listbase_end.end(iter);
}};

private static PropPointerGetFunc SpaceNodeEditor_rna_type_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_builtin_type_get.getPtr(ptr);
}};

private static PropEnumGetFunc SpaceNodeEditor_tree_type_get = new PropEnumGetFunc() {
public int getEnum(PointerRNA ptr)
{
	SpaceNode data= (SpaceNode)(ptr.data);
	return (int)(data.treetype);
}};

private static PropEnumSetFunc SpaceNodeEditor_tree_type_set = new PropEnumSetFunc() {
public void setEnum(PointerRNA ptr, int value)
{
	SpaceNode data= (SpaceNode)(ptr.data);
	value= value;
	data.treetype= castMe(value, data.treetype);
}};

private static PropEnumGetFunc SpaceNodeEditor_texture_type_get = new PropEnumGetFunc() {
public int getEnum(PointerRNA ptr)
{
	SpaceNode data= (SpaceNode)(ptr.data);
	return (int)(data.texfrom);
}};

private static PropEnumSetFunc SpaceNodeEditor_texture_type_set = new PropEnumSetFunc() {
public void setEnum(PointerRNA ptr, int value)
{
	SpaceNode data= (SpaceNode)(ptr.data);
	value= value;
	data.texfrom= castMe(value, data.texfrom);
}};

private static PropPointerGetFunc SpaceNodeEditor_id_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	SpaceNode data= (SpaceNode)(ptr.data);
	return rna_pointer_inherit_refine(ptr, RNA_null, data.id);
}};

private static PropPointerGetFunc SpaceNodeEditor_id_from_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	SpaceNode data= (SpaceNode)(ptr.data);
	return rna_pointer_inherit_refine(ptr, RNA_null, data.from);
}};

private static PropPointerGetFunc SpaceNodeEditor_node_tree_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	SpaceNode data= (SpaceNode)(ptr.data);
	return rna_pointer_inherit_refine(ptr, RNA_null, data.nodetree);
}};

private static PropBooleanGetFunc SpaceNodeEditor_show_backdrop_get = new PropBooleanGetFunc() {
public boolean getBool(PointerRNA ptr)
{
	SpaceNode data= (SpaceNode)(ptr.data);
	return (((data.flag) & 2) != 0);
}};

private static PropBooleanSetFunc SpaceNodeEditor_show_backdrop_set = new PropBooleanSetFunc() {
public void setBool(PointerRNA ptr, boolean value)
{
	SpaceNode data= (SpaceNode)(ptr.data);
	if(value) data.flag |= 2;
	else data.flag &= ~2;
}};

/* Space Node Editor */
private static CollectionPropertyRNA rna_SpaceNodeEditor_rna_properties = new CollectionPropertyRNA(
	null, null,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SpaceNodeEditor_rna_properties_begin, SpaceNodeEditor_rna_properties_next, SpaceNodeEditor_rna_properties_end, SpaceNodeEditor_rna_properties_get, null, null, rna_builtin_properties_lookup_string, RnaProperty.RNA_Property
);

private static PointerPropertyRNA rna_SpaceNodeEditor_rna_type = new PointerPropertyRNA(
	null, null,
	-1, "rna_type", 524288, "RNA",
	"RNA type definition",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SpaceNodeEditor_rna_type_get, null, null, null,RnaStruct.RNA_Struct
);

private static EnumPropertyItem[] rna_SpaceNodeEditor_tree_type_items = {
	new EnumPropertyItem(0, "MATERIAL", 79, "Material", "Material nodes"),
	new EnumPropertyItem(2, "TEXTURE", 80, "Texture", "Texture nodes"),
	new EnumPropertyItem(1, "COMPOSITING", 157, "Compositing", "Compositing nodes"),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_SpaceNodeEditor_tree_type = new EnumPropertyRNA(
	null, null,
	-1, "tree_type", 3, "Tree Type",
	"Node tree type to display and edit",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 252116992, null, null,
	0, -1, null,
	SpaceNodeEditor_tree_type_get, SpaceNodeEditor_tree_type_set, null, rna_SpaceNodeEditor_tree_type_items, 3, 0
);

private static EnumPropertyItem[] rna_SpaceNodeEditor_texture_type_items = {
	new EnumPropertyItem(0, "OBJECT", 159, "Object", "Edit texture nodes from Object"),
	new EnumPropertyItem(1, "WORLD", 158, "World", "Edit texture nodes from World"),
	new EnumPropertyItem(2, "BRUSH", 182, "Brush", "Edit texture nodes from Brush"),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_SpaceNodeEditor_texture_type = new EnumPropertyRNA(
	null, null,
	-1, "texture_type", 3, "Texture Type",
	"Type of data to take texture from",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 252116992, null, null,
	0, -1, null,
	SpaceNodeEditor_texture_type_get, SpaceNodeEditor_texture_type_set, null, rna_SpaceNodeEditor_texture_type_items, 3, 0
);

private static PointerPropertyRNA rna_SpaceNodeEditor_id = new PointerPropertyRNA(
	null, null,
	-1, "id", 0, "ID",
	"Datablock whose nodes are being edited",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SpaceNodeEditor_id_get, null, null, null,null
);

private static PointerPropertyRNA rna_SpaceNodeEditor_id_from = new PointerPropertyRNA(
	null, null,
	-1, "id_from", 0, "ID From",
	"Datablock from which the edited datablock is linked",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SpaceNodeEditor_id_from_get, null, null, null,null
);

private static PointerPropertyRNA rna_SpaceNodeEditor_node_tree = new PointerPropertyRNA(
	null, null,
	-1, "node_tree", 0, "Node Tree",
	"Node tree being displayed and edited",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SpaceNodeEditor_node_tree_get, null, null, null,null
);

private static BooleanPropertyRNA rna_SpaceNodeEditor_show_backdrop = new BooleanPropertyRNA(
	null, null,
	-1, "show_backdrop", 3, "Backdrop",
	"Use active Viewer Node output as backdrop for compositing nodes",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 252772352, null, null,
	0, -1, null,
	SpaceNodeEditor_show_backdrop_get, SpaceNodeEditor_show_backdrop_set, null, null, false, null
);

static { ListBase tmp = new ListBase();
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceNodeEditor_rna_properties);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceNodeEditor_rna_type);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceNodeEditor_tree_type);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceNodeEditor_texture_type);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceNodeEditor_id);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceNodeEditor_id_from);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceNodeEditor_node_tree);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceNodeEditor_show_backdrop);
}

static { ListBase tmp = new ListBase();
}

public static StructRNA RNA_SpaceNodeEditor = new StructRNA(
	RnaUILayout.RNA_UILayout, RnaSpaceInfo.RNA_SpaceInfo,
	null,
	rna_SpaceNodeEditor_rna_properties, rna_SpaceNodeEditor_show_backdrop,
	null,null,
	"SpaceNodeEditor", 0, "Space Node Editor", "Node editor space data",
	17,
	null, rna_SpaceNodeEditor_rna_properties,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null, null
);

}
