
/* Automatically generated struct definitions for the Data API.
   Do not edit manually, changes will be overwritten.           */

package blender.makesrna.srna;

import blender.makesdna.sdna.*;

import static blender.makesrna.RnaRna.*;
import static blender.makesrna.RnaAccess.*;
import static blender.makesrna.RnaDefine.*;
import static blender.makesrna.RNATypes.*;
import blender.makesrna.rna_internal_types.*;
import blender.blenlib.*;
import blender.blenkernel.*;

import static blender.makesrna.RnaSpaceUtil.*;

public class RnaSpaceProperties extends RnaStruct {

/* Autogenerated Functions */

public RnaSpaceProperties(PointerRNA ptr) { super(ptr); }

private static PropCollectionGetFunc SpaceProperties_rna_properties_get = new PropCollectionGetFunc() {
public PointerRNA get(CollectionPropertyIterator iter)
{
	return rna_builtin_properties_get.get(iter);
}};

private static PropCollectionBeginFunc SpaceProperties_rna_properties_begin = new PropCollectionBeginFunc() {
public void begin(CollectionPropertyIterator iter, PointerRNA ptr)
{

	iter.clear();
	iter.parent= ptr;
	iter.prop= (PropertyRNA)rna_SpaceProperties_rna_properties;

	rna_builtin_properties_begin.begin(iter, ptr);

	if(iter.valid)
		iter.ptr= SpaceProperties_rna_properties_get.get(iter);
}};

private static PropCollectionNextFunc SpaceProperties_rna_properties_next = new PropCollectionNextFunc() {
public void next(CollectionPropertyIterator iter)
{
	rna_builtin_properties_next.next(iter);

	if(iter.valid)
		iter.ptr= SpaceProperties_rna_properties_get.get(iter);
}};

private static PropCollectionEndFunc SpaceProperties_rna_properties_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
	rna_iterator_listbase_end.end(iter);
}};

private static PropPointerGetFunc SpaceProperties_rna_type_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_builtin_type_get.getPtr(ptr);
}};

public int getContext() { return SpaceProperties_context_get.getEnum(ptr); }
private static PropEnumGetFunc SpaceProperties_context_get = new PropEnumGetFunc() {
public int getEnum(PointerRNA ptr)
{
	SpaceButs data= (SpaceButs)(ptr.data);
	return (int)(data.mainb);
}};

public void setContext(int value) { SpaceProperties_context_set.setEnum(ptr, value); }
private static PropEnumSetFunc SpaceProperties_context_set = new PropEnumSetFunc() {
public void setEnum(PointerRNA ptr, int value)
{
	SpaceButs data= (SpaceButs)(ptr.data);
	value= value;
	data.mainb= castMe(value, data.mainb);
}};

public int getAlign() { return SpaceProperties_align_get.getEnum(ptr); }
private static PropEnumGetFunc SpaceProperties_align_get = new PropEnumGetFunc() {
public int getEnum(PointerRNA ptr)
{
	SpaceButs data= (SpaceButs)(ptr.data);
	return (int)(data.align);
}};

public void setAlign(int value) { SpaceProperties_align_set.setEnum(ptr, value); }
private static PropEnumSetFunc SpaceProperties_align_set = new PropEnumSetFunc() {
public void setEnum(PointerRNA ptr, int value)
{
	rna_SpaceProperties_align_set.setEnum(ptr, value);
}};

public boolean getShow_brush_texture() { return SpaceProperties_show_brush_texture_get.getBool(ptr); }
private static PropBooleanGetFunc SpaceProperties_show_brush_texture_get = new PropBooleanGetFunc() {
public boolean getBool(PointerRNA ptr)
{
	SpaceButs data= (SpaceButs)(ptr.data);
	return (((data.flag) & 8) != 0);
}};

public void setShow_brush_texture(boolean value) { SpaceProperties_show_brush_texture_set.setBool(ptr, value); }
private static PropBooleanSetFunc SpaceProperties_show_brush_texture_set = new PropBooleanSetFunc() {
public void setBool(PointerRNA ptr, boolean value)
{
	SpaceButs data= (SpaceButs)(ptr.data);
	if(value) data.flag |= 8;
	else data.flag &= ~8;
}};

private static PropPointerGetFunc SpaceProperties_pin_id_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	SpaceButs data= (SpaceButs)(ptr.data);
	return rna_pointer_inherit_refine(ptr, RNA_ID, data.pinid);
}};

private static PropPointerSetFunc SpaceProperties_pin_id_set = new PropPointerSetFunc() {
public void setPtr(PointerRNA ptr, PointerRNA value)
{
	rna_SpaceProperties_pin_id_set.setPtr(ptr, value);
}};

public boolean getUse_pin_id() { return SpaceProperties_use_pin_id_get.getBool(ptr); }
private static PropBooleanGetFunc SpaceProperties_use_pin_id_get = new PropBooleanGetFunc() {
public boolean getBool(PointerRNA ptr)
{
	SpaceButs data= (SpaceButs)(ptr.data);
	return (((data.flag) & 2) != 0);
}};

public void setUse_pin_id(boolean value) { SpaceProperties_use_pin_id_set.setBool(ptr, value); }
private static PropBooleanSetFunc SpaceProperties_use_pin_id_set = new PropBooleanSetFunc() {
public void setBool(PointerRNA ptr, boolean value)
{
	SpaceButs data= (SpaceButs)(ptr.data);
	if(value) data.flag |= 2;
	else data.flag &= ~2;
}};

/* Properties Space */
private static CollectionPropertyRNA rna_SpaceProperties_rna_properties = new CollectionPropertyRNA(
	null, null,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SpaceProperties_rna_properties_begin, SpaceProperties_rna_properties_next, SpaceProperties_rna_properties_end, SpaceProperties_rna_properties_get, null, null, rna_builtin_properties_lookup_string, RnaProperty.RNA_Property
);

private static PointerPropertyRNA rna_SpaceProperties_rna_type = new PointerPropertyRNA(
	null, null,
	-1, "rna_type", 524288, "RNA",
	"RNA type definition",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SpaceProperties_rna_type_get, null, null, null,RnaStruct.RNA_Struct
);

private static EnumPropertyItem[] rna_SpaceProperties_context_items = {
	new EnumPropertyItem(1, "SCENE", 83, "Scene", "Scene"),
	new EnumPropertyItem(0, "RENDER", 156, "Render", "Render"),
	new EnumPropertyItem(2, "WORLD", 82, "World", "World"),
	new EnumPropertyItem(3, "OBJECT", 159, "Object", "Object"),
	new EnumPropertyItem(12, "CONSTRAINT", 175, "Constraints", "Constraints"),
	new EnumPropertyItem(10, "MODIFIER", 286, "Modifiers", "Modifiers"),
	new EnumPropertyItem(4, "DATA", 0, "Data", "Data"),
	new EnumPropertyItem(9, "BONE", 174, "Bone", "Bone"),
	new EnumPropertyItem(13, "BONE_CONSTRAINT", 175, "Bone Constraints", "Bone Constraints"),
	new EnumPropertyItem(5, "MATERIAL", 79, "Material", "Material"),
	new EnumPropertyItem(6, "TEXTURE", 80, "Texture", "Texture"),
	new EnumPropertyItem(7, "PARTICLE", 88, "Particle", "Particle"),
	new EnumPropertyItem(8, "PHYSICS", 89, "Physics", "Physics"),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_SpaceProperties_context = new EnumPropertyRNA(
	null, null,
	-1, "context", 3, "Context",
	"Type of active data to display and edit",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 252313600, null, null,
	0, -1, null,
	SpaceProperties_context_get, SpaceProperties_context_set, null, rna_SpaceProperties_context_items, 13, 0
);

private static EnumPropertyItem[] rna_SpaceProperties_align_items = {
	new EnumPropertyItem(1, "HORIZONTAL", 0, "Horizontal", ""),
	new EnumPropertyItem(2, "VERTICAL", 0, "Vertical", ""),
	new EnumPropertyItem(0, null, 0, null, null)
};

private static EnumPropertyRNA rna_SpaceProperties_align = new EnumPropertyRNA(
	null, null,
	-1, "align", 3, "Align",
	"Arrangement of the panels",
	0,
	PROP_ENUM, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 252313600, null, null,
	0, -1, null,
	SpaceProperties_align_get, SpaceProperties_align_set, null, rna_SpaceProperties_align_items, 2, 1
);

private static BooleanPropertyRNA rna_SpaceProperties_show_brush_texture = new BooleanPropertyRNA(
	null, null,
	-1, "show_brush_texture", 3, "Brush Texture",
	"Show brush textures",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 252313600, null, null,
	0, -1, null,
	SpaceProperties_show_brush_texture_get, SpaceProperties_show_brush_texture_set, null, null, false, null
);

private static PointerPropertyRNA rna_SpaceProperties_pin_id = new PointerPropertyRNA(
	null, null,
	-1, "pin_id", 1, "pin_id",
	"",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	rna_SpaceProperties_pin_id_update, 252313600, null, null,
	0, -1, null,
	SpaceProperties_pin_id_get, SpaceProperties_pin_id_set, rna_SpaceProperties_pin_id_typef, null,RNA_ID
);

private static BooleanPropertyRNA rna_SpaceProperties_use_pin_id = new BooleanPropertyRNA(
	null, null,
	-1, "use_pin_id", 3, "Pin ID",
	"Use the pinned context",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SpaceProperties_use_pin_id_get, SpaceProperties_use_pin_id_set, null, null, false, null
);

static { ListBase tmp = new ListBase();
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceProperties_rna_properties);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceProperties_rna_type);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceProperties_context);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceProperties_align);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceProperties_show_brush_texture);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceProperties_pin_id);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceProperties_use_pin_id);
}

static { ListBase tmp = new ListBase();
}

public static StructRNA RNA_SpaceProperties = new StructRNA(
	RnaSpaceTimeline.RNA_SpaceTimeline, RNA_Region,
	null,
	rna_SpaceProperties_rna_properties, rna_SpaceProperties_use_pin_id,
	null,null,
	"SpaceProperties", 0, "Properties Space", "Properties space data",
	17,
	null, rna_SpaceProperties_rna_properties,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null, null
);

}
