
/* Automatically generated struct definitions for the Data API.
   Do not edit manually, changes will be overwritten.           */

package blender.makesrna.srna;

import blender.makesdna.sdna.*;

import static blender.makesrna.RnaRna.*;
import static blender.makesrna.RnaAccess.*;
import static blender.makesrna.RnaDefine.*;
import static blender.makesrna.RNATypes.*;
import blender.makesrna.rna_internal_types.*;
import blender.blenlib.*;
import blender.blenkernel.*;

import static blender.makesrna.RnaSpaceUtil.*;

public class RnaSpaceInfo extends RnaStruct {

/* Autogenerated Functions */

public RnaSpaceInfo(PointerRNA ptr) { super(ptr); }

private static PropCollectionGetFunc SpaceInfo_rna_properties_get = new PropCollectionGetFunc() {
public PointerRNA get(CollectionPropertyIterator iter)
{
	return rna_builtin_properties_get.get(iter);
}};

private static PropCollectionBeginFunc SpaceInfo_rna_properties_begin = new PropCollectionBeginFunc() {
public void begin(CollectionPropertyIterator iter, PointerRNA ptr)
{

	iter.clear();
	iter.parent= ptr;
	iter.prop= (PropertyRNA)rna_SpaceInfo_rna_properties;

	rna_builtin_properties_begin.begin(iter, ptr);

	if(iter.valid)
		iter.ptr= SpaceInfo_rna_properties_get.get(iter);
}};

private static PropCollectionNextFunc SpaceInfo_rna_properties_next = new PropCollectionNextFunc() {
public void next(CollectionPropertyIterator iter)
{
	rna_builtin_properties_next.next(iter);

	if(iter.valid)
		iter.ptr= SpaceInfo_rna_properties_get.get(iter);
}};

private static PropCollectionEndFunc SpaceInfo_rna_properties_end = new PropCollectionEndFunc() {
public void end(CollectionPropertyIterator iter)
{
	rna_iterator_listbase_end.end(iter);
}};

private static PropPointerGetFunc SpaceInfo_rna_type_get = new PropPointerGetFunc() {
public PointerRNA getPtr(PointerRNA ptr)
{
	return rna_builtin_type_get.getPtr(ptr);
}};

private static PropBooleanGetFunc SpaceInfo_show_report_debug_get = new PropBooleanGetFunc() {
public boolean getBool(PointerRNA ptr)
{
	SpaceInfo data= (SpaceInfo)(ptr.data);
	return (((data.rpt_mask) & 1) != 0);
}};

private static PropBooleanSetFunc SpaceInfo_show_report_debug_set = new PropBooleanSetFunc() {
public void setBool(PointerRNA ptr, boolean value)
{
	SpaceInfo data= (SpaceInfo)(ptr.data);
	if(value) data.rpt_mask |= 1;
	else data.rpt_mask &= ~1;
}};

private static PropBooleanGetFunc SpaceInfo_show_report_info_get = new PropBooleanGetFunc() {
public boolean getBool(PointerRNA ptr)
{
	SpaceInfo data= (SpaceInfo)(ptr.data);
	return (((data.rpt_mask) & 2) != 0);
}};

private static PropBooleanSetFunc SpaceInfo_show_report_info_set = new PropBooleanSetFunc() {
public void setBool(PointerRNA ptr, boolean value)
{
	SpaceInfo data= (SpaceInfo)(ptr.data);
	if(value) data.rpt_mask |= 2;
	else data.rpt_mask &= ~2;
}};

private static PropBooleanGetFunc SpaceInfo_show_report_operator_get = new PropBooleanGetFunc() {
public boolean getBool(PointerRNA ptr)
{
	SpaceInfo data= (SpaceInfo)(ptr.data);
	return (((data.rpt_mask) & 4) != 0);
}};

private static PropBooleanSetFunc SpaceInfo_show_report_operator_set = new PropBooleanSetFunc() {
public void setBool(PointerRNA ptr, boolean value)
{
	SpaceInfo data= (SpaceInfo)(ptr.data);
	if(value) data.rpt_mask |= 4;
	else data.rpt_mask &= ~4;
}};

private static PropBooleanGetFunc SpaceInfo_show_report_warning_get = new PropBooleanGetFunc() {
public boolean getBool(PointerRNA ptr)
{
	SpaceInfo data= (SpaceInfo)(ptr.data);
	return (((data.rpt_mask) & 8) != 0);
}};

private static PropBooleanSetFunc SpaceInfo_show_report_warning_set = new PropBooleanSetFunc() {
public void setBool(PointerRNA ptr, boolean value)
{
	SpaceInfo data= (SpaceInfo)(ptr.data);
	if(value) data.rpt_mask |= 8;
	else data.rpt_mask &= ~8;
}};

private static PropBooleanGetFunc SpaceInfo_show_report_error_get = new PropBooleanGetFunc() {
public boolean getBool(PointerRNA ptr)
{
	SpaceInfo data= (SpaceInfo)(ptr.data);
	return (((data.rpt_mask) & 16) != 0);
}};

private static PropBooleanSetFunc SpaceInfo_show_report_error_set = new PropBooleanSetFunc() {
public void setBool(PointerRNA ptr, boolean value)
{
	SpaceInfo data= (SpaceInfo)(ptr.data);
	if(value) data.rpt_mask |= 16;
	else data.rpt_mask &= ~16;
}};

/* Space Info */
private static CollectionPropertyRNA rna_SpaceInfo_rna_properties = new CollectionPropertyRNA(
	null, null,
	-1, "rna_properties", 128, "Properties",
	"RNA property collection",
	0,
	PROP_COLLECTION, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SpaceInfo_rna_properties_begin, SpaceInfo_rna_properties_next, SpaceInfo_rna_properties_end, SpaceInfo_rna_properties_get, null, null, rna_builtin_properties_lookup_string, RnaProperty.RNA_Property
);

private static PointerPropertyRNA rna_SpaceInfo_rna_type = new PointerPropertyRNA(
	null, null,
	-1, "rna_type", 524288, "RNA",
	"RNA type definition",
	0,
	PROP_POINTER, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 0, null, null,
	0, -1, null,
	SpaceInfo_rna_type_get, null, null, null,RnaStruct.RNA_Struct
);

private static BooleanPropertyRNA rna_SpaceInfo_show_report_debug = new BooleanPropertyRNA(
	null, null,
	-1, "show_report_debug", 3, "Show Debug",
	"Display debug reporting info",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 251789312, null, null,
	0, -1, null,
	SpaceInfo_show_report_debug_get, SpaceInfo_show_report_debug_set, null, null, false, null
);

private static BooleanPropertyRNA rna_SpaceInfo_show_report_info = new BooleanPropertyRNA(
	null, null,
	-1, "show_report_info", 3, "Show Info",
	"Display general information",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 251789312, null, null,
	0, -1, null,
	SpaceInfo_show_report_info_get, SpaceInfo_show_report_info_set, null, null, false, null
);

private static BooleanPropertyRNA rna_SpaceInfo_show_report_operator = new BooleanPropertyRNA(
	null, null,
	-1, "show_report_operator", 3, "Show Operator",
	"Display the operator log",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 251789312, null, null,
	0, -1, null,
	SpaceInfo_show_report_operator_get, SpaceInfo_show_report_operator_set, null, null, false, null
);

private static BooleanPropertyRNA rna_SpaceInfo_show_report_warning = new BooleanPropertyRNA(
	null, null,
	-1, "show_report_warning", 3, "Show Warn",
	"Display warnings",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 251789312, null, null,
	0, -1, null,
	SpaceInfo_show_report_warning_get, SpaceInfo_show_report_warning_set, null, null, false, null
);

private static BooleanPropertyRNA rna_SpaceInfo_show_report_error = new BooleanPropertyRNA(
	null, null,
	-1, "show_report_error", 3, "Show Error",
	"Display error text",
	0,
	PROP_BOOLEAN, PROP_NONE|PROP_UNIT_NONE, null, 0, new int[]{0, 0, 0}, 0,
	null, 251789312, null, null,
	0, -1, null,
	SpaceInfo_show_report_error_get, SpaceInfo_show_report_error_set, null, null, false, null
);

static { ListBase tmp = new ListBase();
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceInfo_rna_properties);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceInfo_rna_type);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceInfo_show_report_debug);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceInfo_show_report_info);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceInfo_show_report_operator);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceInfo_show_report_warning);
	ListBaseUtil.BLI_addtail(tmp, rna_SpaceInfo_show_report_error);
}

static { ListBase tmp = new ListBase();
}

public static StructRNA RNA_SpaceInfo = new StructRNA(
	RnaSpaceNodeEditor.RNA_SpaceNodeEditor, RnaSpaceTimeline.RNA_SpaceTimeline,
	null,
	rna_SpaceInfo_rna_properties, rna_SpaceInfo_show_report_error,
	null,null,
	"SpaceInfo", 0, "Space Info", "Info space data",
	17,
	null, rna_SpaceInfo_rna_properties,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null, null
);

}
